services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # ports:
    #   - "42070:42070"
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/aginTV
      - PORT=42070
    restart: always
    labels:
      traefik.enable: true
      traefik.port: 42070
      traefik.http.services.agintvapi.loadbalancer.server.port: "42070"
      traefik.http.routers.agintvapi.rule: "Host(`api.tv.agin.rocks`)"
    networks:
      - default
      - proxy
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    # ports:
    #   - "8894:3000"
    restart: always
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.http.services.agintv.loadbalancer.server.port: "3000"
      traefik.http.routers.agintv.rule: "Host(`tv.agin.rocks`)"
    networks:
      - default
      - proxy
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      - type: bind
        source: ./db
        target: /data/db
    ports:
      - ":27017"
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=agin
    #   - MONGODB_INITDB_ROOT_PASSWORD=agin
    restart: always
    user: 1000:1000
    networks:
      - default
networks:
  default:
  proxy:
    name: proxy-network
    external: true
